//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArticleLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebArticleLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Dear {0} {1}, please confirm your account, using this link: &lt;a href=&apos;{2}&apos;&gt;Confirm&lt;/a&gt;&lt;br /&gt;The link is available until &lt;span style=&apos;color:red&apos;&gt;{3}&lt;/span&gt;&lt;br/&gt;If you didn&apos;t register on the site, merely ignore this message&lt;/b&gt;.
        /// </summary>
        internal static string Authentication_Register_Message {
            get {
                return ResourceManager.GetString("Authentication_Register_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Dear {0} {1}, there have been alterations made to your account: &lt;span style=&apos;color:red&apos;&gt;{2}&lt;/span&gt;. Please, use our contact page to get more information: &lt;a href=&apos;{3}&apos;&gt;Contact Us&lt;/a&gt;&lt;/b&gt;.
        /// </summary>
        internal static string UserInfo_AccountChanges_Message {
            get {
                return ResourceManager.GetString("UserInfo_AccountChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Dear {0} {1}, please confirm your new email, using this link: &lt;a href=&apos;{2}&apos;&gt;Confirm&lt;/a&gt;&lt;br /&gt;The link is available until &lt;span style=&apos;color:red&apos;&gt;{3}&lt;/span&gt;&lt;/b&gt;.
        /// </summary>
        internal static string UserInfo_NewEmail_Message {
            get {
                return ResourceManager.GetString("UserInfo_NewEmail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Dear {0} {1}, please reset your current password, using this link: &lt;a href=&apos;{2}&apos;&gt;Reset&lt;/a&gt;&lt;br /&gt;The link is available until &lt;span style=&apos;color:red&apos;&gt;{3}&lt;/span&gt;&lt;/b&gt;.
        /// </summary>
        internal static string UserInfo_ResetPassword_Message {
            get {
                return ResourceManager.GetString("UserInfo_ResetPassword_Message", resourceCulture);
            }
        }
    }
}
