// <auto-generated />
namespace WebArticleLibrary.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ARTICLE_DESCRIPTION_FIELD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ARTICLE_DESCRIPTION_FIELD));
        
        string IMigrationMetadata.Id
        {
            get { return "201710011035346_ARTICLE_DESCRIPTION_FIELD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
