// <auto-generated />
namespace WebArticleLibrary.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ARTICLE_ASSIGNED_USER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ARTICLE_ASSIGNED_USER));
        
        string IMigrationMetadata.Id
        {
            get { return "201705211557140_ARTICLE_ASSIGNED_USER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
