// <auto-generated />
namespace WebArticleLibrary.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class USER_COMMENT_AND_ESTIMATE_TABLES : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(USER_COMMENT_AND_ESTIMATE_TABLES));
        
        string IMigrationMetadata.Id
        {
            get { return "201707212022347_USER_COMMENT_AND_ESTIMATE_TABLES"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
