// <auto-generated />
namespace WebArticleLibrary.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class USER_RESETTING_PASSWORD_PARAMS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(USER_RESETTING_PASSWORD_PARAMS));
        
        string IMigrationMetadata.Id
        {
            get { return "201704122028535_USER_RESETTING_PASSWORD_PARAMS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
